In [1]:
import sys
sys.path.insert(0, './renderer')
sys.path.insert(0, '../')

"""
PyTorch 的 collections 库提供了一些用于管理和操作 Python 集合的工具。
namedtuple: 用于创建具有命名属性的元组。
"""
from collections import namedtuple
import render_car_instances as rci
import utils.utils as uts

Setting = namedtuple('Setting', ['image_name', 'data_dir'])
setting = Setting('180116_053947113_Camera_5', '../apolloscape/sample/')
# /home/yang/Datasets/ApolloScape/CarInstance/sample/car_models//baojun-310-2017.pkl
# setting = Setting('180116_053947113_Camera_5', '/home/yang/Datasets/ApolloScape/CarInstance/sample/')


"""
matplotlib inline是IPython的魔法函数,
可以在IPython编译器里直接使用,作用是内嵌画图,省略掉plt.show()这一步，直接显示图像。
"""
%matplotlib inline
visualizer = rci.CarPoseVisualizer(setting) # 初始化类，获得数据集的地址，内外参，分辨率等信息
visualizer.load_car_models_json()
# image_vis, mask, depth = visualizer.showAnn(setting.image_name)


INFO:root:loading 79 car models


In [16]:
# image_vis, mask, depth = visualizer.showAnn(setting.image_name)
import numpy as np
temp = np.array([[1,0,1,0],[1,1,1,0]])
depth = 5 * np.ones(temp.shape)
depth_arr = np.concatenate([temp[None, :, :], depth[None, :, :]], axis=0)
idx = np.argmin(depth_arr, axis=0)
total_depth = np.amin(depth_arr, axis=0)
print(depth_arr.shape)
print(idx)
print(total_depth)

(2, 2, 4)
[[0 0 0 0]
 [0 0 0 0]]
[[1. 0. 1. 0.]
 [1. 1. 1. 0.]]
